---
# Variables globales
wordpress_domain: "wordpress.local"
wordpress_admin_email: "admin@wordpress.local"

# Directorio de instalaci贸n
wordpress_install_dir: "/var/www/html/wordpress"
wordpress_document_root: "/var/www/html"

# Configuraci贸n de PHP (actualizado a 8.1)
php_version: "8.1"

# Servidor web preferido
webserver_type: "apache"

# WordPress configuraci贸n de debug (simplificado para capacitaci贸n)
wordpress_debug: false
wordpress_debug_log: false