---
# group_vars/wordpress.xml
# Variables específicas solo para el grupo 'wordpress'

# WordPress configuración específica
wordpress_install_dir: "/var/www/html/wordpress"
wordpress_document_root: "/var/www/html"
wordpress_table_prefix: "wp_"
wordpress_debug: false
wordpress_debug_log: false

# WordPress security keys (específicas de este ambiente)
wordpress_auth_key: "tu-auth-key-aqui"
wordpress_secure_auth_key: "tu-secure-auth-key-aqui" 
wordpress_logged_in_key: "tu-logged-in-key-aqui"
wordpress_nonce_key: "tu-nonce-key-aqui"
wordpress_auth_salt: "tu-auth-salt-aqui"
wordpress_secure_auth_salt: "tu-secure-auth-salt-aqui"
wordpress_logged_in_salt: "tu-logged-in-salt-aqui"
wordpress_nonce_salt: "tu-nonce-salt-aqui"

# WordPress versión y descarga
wordpress_version: "latest"
wordpress_download_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"

# Apache configuración específica (si usas geerlingguy.apache en el futuro)
apache_vhosts:
  - servername: "{{ wordpress_domain }}"
    documentroot: "{{ wordpress_install_dir }}"
    extra_parameters: |
      <Directory "{{ wordpress_install_dir }}">
          AllowOverride All
          Require all granted
      </Directory>