---
all:
  children:
    wordpress:
      hosts:
        ubuntu:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/ubuntu/virtualbox/private_key
        debian:
          ansible_host: 192.168.56.11
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/debian/virtualbox/private_key
        rocky:
          ansible_host: 192.168.56.12
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/rocky/virtualbox/private_key
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'