---
# Tareas específicas para Debian/Ubuntu

- name: "Actualizar cache de apt"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: ['packages']

- name: "Instalar paquetes necesarios para WordPress"
  apt:
    name: "{{ debian_packages }}"
    state: present
  tags: ['packages']

- name: "Habilitar módulos de Apache"
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - ssl
    - headers
  notify: restart apache2
  tags: ['apache', 'modules']

- name: "Crear directorio de WordPress"
  file:
    path: "{{ wordpress_install_dir }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
    mode: '0755'
  tags: ['wordpress', 'directories']