---
# Tareas específicas para Debian/Ubuntu

- name: "Actualizar cache de apt"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: ["packages"]

- name: "Instalar paquetes necesarios para WordPress"
  ansible.builtin.apt:
    name: "{{ debian_packages }}"
    state: present
  tags: ["packages"]

- name: "Habilitar módulos de Apache"
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - ssl
    - headers
  notify: restart apache2
  tags: ["apache", "modules"]

- name: "Crear directorio de WordPress"
  ansible.builtin.file:
    path: "{{ wordpress_install_dir }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
    mode: "0755"
  tags: ["wordpress", "directories"]
