---
# Tareas principales del role webserver

- name: "Detectar versión de PHP disponible"
  include_tasks: detect-php-version.yml
  tags: ['always']

- name: "Incluir variables específicas por OS"
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: ['always']

- name: "Instalar paquetes web server y PHP (Debian/Ubuntu)"
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags: ['packages', 'php']

- name: "Instalar paquetes web server y PHP (RedHat/CentOS)"
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
  tags: ['packages', 'php']

- name: "Configurar PHP"
  include_tasks: php.yml
  tags: ['php', 'config']

- name: "Instalar y configurar WordPress"
  include_tasks: wordpress.yml
  tags: ['wordpress']

- name: "Asegurar que servicios estén iniciados"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ webserver_services }}"
  tags: ['services']
