---
# Tareas específicas para RedHat/CentOS/Rocky

- name: "Instalar repositorio EPEL"
  yum:
    name: epel-release
    state: present
  when: ansible_distribution_major_version | int >= 8
  tags: ['packages', 'repo']

- name: "Instalar repositorio Remi para PHP"
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present
    disable_gpg_check: yes
  tags: ['packages', 'repo']

- name: "Habilitar módulo PHP Remi"
  command: "dnf module enable php:remi-{{ php_version | replace('.', '') }} -y"
  when: ansible_distribution_major_version | int >= 8
  changed_when: false
  tags: ['packages', 'repo']

- name: "Instalar paquetes necesarios para WordPress"
  yum:
    name: "{{ redhat_packages }}"
    state: present
  tags: ['packages']

- name: "Configurar firewall para HTTP/HTTPS"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - http
    - https
  ignore_errors: yes
  tags: ['firewall']

- name: "Configurar SELinux para WordPress"
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
  ignore_errors: yes
  tags: ['selinux']

- name: "Crear directorio de WordPress"
  file:
    path: "{{ wordpress_install_dir }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
    mode: '0755'
    setype: httpd_exec_t
  tags: ['wordpress', 'directories']