---
# Tareas específicas para RedHat/CentOS/Rocky

- name: "Instalar repositorio EPEL"
  dnf:
    name: epel-release
    state: present
  tags: ['packages', 'repo']

- name: "Instalar paquetes necesarios para WordPress"
  dnf:
    name: "{{ redhat_packages }}"
    state: present
  tags: ['packages']

- name: "Configurar firewall para HTTP/HTTPS"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - http
    - https
  ignore_errors: yes
  tags: ['firewall']

- name: "Configurar SELinux para WordPress (básico)"
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
  ignore_errors: yes
  tags: ['selinux']

- name: "Crear directorio de WordPress"
  file:
    path: "{{ wordpress_install_dir }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
    mode: '0755'
  tags: ['wordpress', 'directories']