---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Include webserver role
      include_role:
        name: webserver
      vars:
        # Variables que se pasan al role (de molecule.yml)
        wordpress_domain: "{{ wordpress_domain | default('test.local') }}"
        wordpress_install_dir: "/var/www/html/wordpress"
        php_version: "{{ php_version | default('8.2') }}"
        webserver_type: "apache"
        
        # Database connection
        wordpress_db_host: "{{ wordpress_db_host | default('localhost') }}"
        wordpress_db_name: "{{ wordpress_db_name | default('test_wordpress_db') }}"
        wordpress_db_user: "{{ wordpress_db_user | default('test_wp_user') }}"
        wordpress_db_password: "{{ wordpress_db_password | default('test_wp_password') }}"
        
        # WordPress config para testing
        wordpress_table_prefix: "test_wp_"
        wordpress_debug: true
        
        # Security keys simplificadas para testing
        wordpress_auth_key: "test-auth-key-molecule"
        wordpress_secure_auth_key: "test-secure-auth-key-molecule"
        wordpress_logged_in_key: "test-logged-in-key-molecule"
        wordpress_nonce_key: "test-nonce-key-molecule"
        wordpress_auth_salt: "test-auth-salt-molecule"
        wordpress_secure_auth_salt: "test-secure-auth-salt-molecule"
        wordpress_logged_in_salt: "test-logged-in-salt-molecule"
        wordpress_nonce_salt: "test-nonce-salt-molecule"
