---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Install MySQL connector for Python
      pip:
        name: PyMySQL
        state: present
        
    - name: Install and configure MySQL
      include_role:
        name: geerlingguy.mysql

    - name: Wait for MySQL to be ready
      wait_for:
        port: 3306
        host: localhost
        timeout: 60
        
    - name: Verify MySQL is running
      systemd:
        name: mysql
        state: started
        enabled: yes
